services:
  routine-impulse:
    image: routine-impulse:latest
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    secrets:
      - jwt_private_key
      - jwt_public_key
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  jwt_private_key:
    file: ${JWT_PRIVATE_KEY_FILE}
  jwt_public_key:
    file: ${JWT_PUBLIC_KEY_FILE}
