# General
quarkus.application.name=Routine Impulse
quarkus.log.level=INFO
quarkus.http.port=8080

# Banner
quarkus.banner.enabled=true
quarkus.banner.path=banner.txt

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

# Security
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.issuer=routine-impulse
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=access_token
smallrye.jwt.sign.key.location=/run/secrets/jwt_private_key
smallrye.jwt.verify.key.location=/run/secrets/jwt_public_key

quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated

quarkus.http.auth.permission.auth.paths=/api/auth/*
quarkus.http.auth.permission.auth.policy=permit
quarkus.http.auth.proactive=false
